server:
  port: 8000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.tsien.vhr: debug
  path: ./logs

spring:
  profiles:
    active: prod

---
spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://localhost:3306/vhr?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 16601130186
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  profiles: prod

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app-name: TsienMall
  author: Tsien
  email: tsien16@qq.com
