# \u901A\u7528\u914D\u7F6E
server:
  port: 8000

# \u5176\u5B83\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.tsien.mall: debug
  path: ./logs

spring:
  profiles:
    active: prod

---
spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://localhost:3306/vhr?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 16601130186
  jackson:
    default-property-inclusion: non_null # \u5E8F\u5217\u5316\u65F6\u5019\uFF0C\u5B57\u6BB5\u4E3A\u7A7A\u65F6\u5019\uFF0Ckey\u4E0D\u663E\u793A
  servlet:
    multipart: # \u6587\u4EF6\u4E0A\u4F20\u914D\u7F6E
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  profiles: prod

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app-name: TsienMall
  author: Tsien
  email: tsien16@qq.com
