server:
  port: 8000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.tsien.vhr: info
  file:
    path: ./logs

spring:
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

---
spring:
  datasource:
    druid:
      name: druidDatasource
      url: jdbc:mysql://localhost:3306/vhr?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 18896727773
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  mail:
    host: smtp.qq.com
    port: 465
    username: tsien16@qq.com
    password: hlcwbnkoxprtbjhc
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

  profiles: prod
